// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.firebears.subsystems;


import org.firebears.RobotMap;
import org.firebears.util.SoftFuse;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class Bail extends PIDSubsystem {

	/** Minimum value that the setpoint may take, measured in volts. */
	public double MIN_VALUE;

	/** Maximum value that the setpoint may take, measured in volts. */
	public double MAX_VALUE;

	/** Maximum speed that the motor can turn, in the range 0.0 to 1.0. */
	public double MAX_SPEED;

	public double PARK_VALUE;	
	SoftFuse softFuse;
	
	public Bail() {
		super(0.5, 0, 0);
//		super(1.50, 0.03, 5.0);

		MAX_SPEED = 1.;
		MIN_VALUE = 0.;
		MAX_VALUE = 0.;
		PARK_VALUE = 0.;
		
		softFuse = new SoftFuse(bail, 40, 1, 2);

		getPIDController().setInputRange(MIN_VALUE, MAX_VALUE);
		getPIDController().setAbsoluteTolerance(0.01);
		getPIDController().setToleranceBuffer(8);
		setSetpoint(PARK_VALUE);
		getPIDController().enable();
		softFuse.positionFuse(bail.getOutputCurrent());

		LiveWindow.addActuator("Bail", "PIDSubsystem Controller", getPIDController());
	}

	private final CANTalon bail = RobotMap.bail;
	private final AnalogInput pot = RobotMap.bailPos;

	public void initDefaultCommand() {
	}

	@Override
	protected double returnPIDInput() {
		return pot.getAverageVoltage();
	}

	@Override
	protected void usePIDOutput(double output) {
		output = Math.max((MAX_SPEED * -1), Math.min(output, MAX_SPEED));
		CANTalon bailPos;
		bail.set(output);
	}

	public void park(){
		setSetpoint(PARK_VALUE);
		softFuse.positionFuse(bail.getOutputCurrent());

	}

}
