// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.firebears.subsystems;

import org.firebears.RobotMap;
import org.firebears.commands.*;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 * Subsystem for retrieving boulders.
 */
public class BallGetter extends Subsystem {

    private final CANTalon sideMotor = RobotMap.ballGetterSideMotor;
    private final CANTalon frontMotor = RobotMap.ballGetterFrontMotor;
    private final CANTalon angleMotor = RobotMap.ballGetterAngleMotor;
    private final AnalogInput pot = RobotMap.ballGetterAnalogInput;

    public BallGetter() {
    	super();
    }


    public void initDefaultCommand() { }
}

