// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.firebears.subsystems;


import static org.firebears.RobotMap.getPreferencesDouble;

import org.firebears.RobotMap;
import org.firebears.util.SoftFuse;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Servo;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class Bail extends Subsystem {

	/** Minimum value that the setpoint may take, measured in volts. */
	public double MIN_VALUE;

	/** Maximum value that the setpoint may take, measured in volts. */
//<<<<<<< HEAD
	public final double MAX_VALUE;
//=======
//	public double MAX_VALUE;
//>>>>>>> branch 'master' of https://github.com/firebears-frc/FB2016.git
	
	public double PRE_SHOOT_VALUE;

	public double PARK_VALUE;	

	private Servo bailServo;
	
	
	
	
	public Bail() {
//		

		
//<<<<<<< HEAD
		MIN_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_MIN_VALUE,1.5);  // Pot value to reset bail onto the floor
		PRE_SHOOT_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_PRESHOOT_VALUE,1.0);  // Pot value to hold ball before shooting
		PARK_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_PARK_VALUE,1.0); // Pot value to hold onto the ball while driving
		MAX_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_MAX_VALUE,0.4);  // Pot value to fire the ball

//=======
//		MIN_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_MIN_VALUE,1.5);  // Pot value to reset bail onto the floor
////		PRE_SHOOT_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_PRESHOOT_VALUE,1.0);  // Pot value to hold ball before shooting
////		PARK_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_PARK_VALUE,1.0); // Pot value to hold onto the ball while driving
////		MAX_VALUE = getPreferencesDouble(RobotMap.PREF_BAIL_MAX_VALUE,0.4);  // Pot value to fire the ball
//		PARK_VALUE = 2.60; // Pot value to hold onto the ball while driving
//		PRE_SHOOT_VALUE = 2.91; // Pot value to hold ball before shooting
//		MIN_VALUE = 3.00; // Pot value to reset bail onto the floor
//		MAX_VALUE = 2.25; // Pot value to fire the ball
//>>>>>>> branch 'master' of https://github.com/firebears-frc/FB2016.git
		bailServo = RobotMap.shooterServo;
		addChild("Servo", bailServo);
	}

	

	public void initDefaultCommand() {
	}



	

	/** Lower the bail so we can pick up the ball. */
	public void reset(){
		System.out.println("Bail.Reset");
		//setSetpoint(MIN_VALUE);
		
	}
	
	/** Raise the bail slightly to hold onto the ball. */
	public void hold(){
		System.out.println("Bail.hold");
		//setSetpoint(PARK_VALUE);
		 
	}
	
	/** Lower ball just before shooting */
	public void preShoot(){
		System.out.println("Bail.preshoot");
		//setSetpoint(PRE_SHOOT_VALUE);//PRE_SHOOT_VALUE
		 
	}
	
	/** Raise the bail to fire the shooter. */
	public void fire(){
		//setSetpoint(MAX_VALUE);//MAX_VALUE
		System.out.println("Bail.fire/max: " + MAX_VALUE);
		 
	}
	

}
